# Comparison between synthetic and real data
The objective is to compare synthetic dataset with the real one to identify the differences in distributions and relations between the correspondent variables.

In [1]:
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import sweetviz as sv

## Bivariate fidelity

In [2]:
synth_data = joblib.load('../outputs/models/train_data.pkl')
real_data = joblib.load('../outputs/models/test_data.pkl')

In [3]:
real_data.columns = real_data.columns.sort_values(ascending=True)

In [4]:
synth_data.columns = synth_data.columns.sort_values(ascending=True)

In [5]:
real_data.corr()

,P_WH_after,P_WH_before,P_WH_delta,P_Z0_after,P_Z0_before,P_Z0_delta,P_Z1_after,P_Z1_before,P_Z1_delta,P_bottom_after,...,action_result,bottom_icv_status_after,bottom_icv_status_before,command_type_0,command_type_1,command_type_2,command_type_3,command_type_4,top_icv_status_after,top_icv_status_before
P_WH_after,1.000000,0.806118,-0.318992,1.000000,0.806118,-0.318992,1.000000,0.806118,-0.318992,0.204532,...,0.207434,0.444092,0.350237,0.460650,0.244639,-0.134403,0.104095,0.229944,-0.126731,-0.280525
P_WH_before,0.806118,1.000000,0.303694,0.806118,1.000000,0.303694,0.806118,1.000000,0.303694,0.288120,...,0.265633,0.440419,0.266300,0.546888,0.182636,-0.020221,-0.042054,0.294182,-0.096359,-0.332556
P_WH_delta,-0.318992,0.303694,1.000000,-0.318992,0.303694,1.000000,-0.318992,0.303694,1.000000,0.132143,...,0.091453,-0.009644,-0.137401,0.134217,-0.101376,0.184013,-0.234956,0.100936,0.049717,-0.080956
P_Z0_after,1.000000,0.806118,-0.318992,1.000000,0.806118,-0.318992,1.000000,0.806118,-0.318992,0.204532,...,0.207434,0.444092,0.350237,0.460650,0.244639,-0.134403,0.104095,0.229944,-0.126731,-0.280525
P_Z0_before,0.806118,1.000000,0.303694,0.806118,1.000000,0.303694,0.806118,1.000000,0.303694,0.288120,...,0.265633,0.440419,0.266300,0.546888,0.182636,-0.020221,-0.042054,0.294182,-0.096359,-0.332556
P_Z0_delta,-0.318992,0.303694,1.000000,-0.318992,0.303694,1.000000,-0.318992,0.303694,1.000000,0.132143,...,0.091453,-0.009644,-0.137401,0.134217,-0.101376,0.184013,-0.234956,0.100936,0.049717,-0.080956
P_Z1_after,1.000000,0.806118,-0.318992,1.000000,0.806118,-0.318992,1.000000,0.806118,-0.318992,0.204532,...,0.207434,0.444092,0.350237,0.460650,0.244639,-0.134403,0.104095,0.229944,-0.126731,-0.280525
P_Z1_before,0.806118,1.000000,0.303694,0.806118,1.000000,0.303694,0.806118,1.000000,0.303694,0.288120,...,0.265633,0.440419,0.266300,0.546888,0.182636,-0.020221,-0.042054,0.294182,-0.096359,-0.332556
P_Z1_delta,-0.318992,0.303694,1.000000,-0.318992,0.303694,1.000000,-0.318992,0.303694,1.000000,0.132143,...,0.091453,-0.009644,-0.137401,0.134217,-0.101376,0.184013,-0.234956,0.100936,0.049717,-0.080956
P_bottom_after,0.204532,0.288120,0.132143,0.204532,0.288120,0.132143,0.204532,0.288120,0.132143,1.000000,...,0.331242,0.354550,0.219843,0.367365,0.167221,-0.116263,-0.141119,0.336842,-0.074165,-0.295581
P_bottom_before,0.322117,0.208761,-0.184281,0.322117,0.208761,-0.184281,0.322117,0.208761,-0.184281,0.776935,...,0.291667,0.323289,0.247293,0.327740,0.217569,-0.118039,-0.063828,0.301370,-0.126267,-0.255542
P_bottom_delta,0.117574,-0.068358,-0.298786,0.117574,-0.068358,-0.298786,0.117574,-0.068358,-0.298786,-0.377049,...,-0.055227,-0.044987,-0.130725,-0.110930,-0.064332,-0.003242,0.111650,-0.046867,-0.082516,0.058089
T_WH_after,-0.820202,-0.636984,0.300389,-0.820202,-0.636984,0.300389,-0.820202,-0.636984,0.300389,-0.224960,...,-0.121191,-0.421173,-0.337553,-0.431646,-0.240105,0.156235,-0.236063,-0.155307,0.132460,0.261696
T_WH_before,-0.560846,-0.613648,-0.079819,-0.560846,-0.613648,-0.079819,-0.560846,-0.613648,-0.079819,-0.259657,...,-0.169190,-0.313788,-0.221918,-0.381905,-0.156077,0.029499,-0.028364,-0.192236,0.096847,0.226692
T_WH_delta,0.151337,-0.063358,-0.345137,0.151337,-0.063358,-0.345137,0.151337,-0.063358,-0.345137,-0.080182,...,-0.058834,0.057252,0.150844,0.060484,0.047056,-0.108440,0.200424,-0.068357,0.026381,-0.045559
T_Z0_after,-0.927619,-0.763922,0.270034,-0.927619,-0.763922,0.270034,-0.927619,-0.763922,0.270034,-0.266794,...,-0.141843,-0.411342,-0.324906,-0.434576,-0.228134,0.147921,-0.169453,-0.174323,0.107952,0.260998
T_Z0_before,-0.626080,-0.673569,-0.070757,-0.626080,-0.673569,-0.070757,-0.626080,-0.673569,-0.070757,-0.278790,...,-0.169564,-0.299972,-0.207281,-0.363012,-0.144634,0.015962,0.002690,-0.193359,0.080973,0.222294
T_Z0_delta,0.033314,-0.150953,-0.295405,0.033314,-0.150953,-0.295405,0.033314,-0.150953,-0.295405,-0.143972,...,-0.086585,-0.001467,-0.054342,-0.064206,-0.097554,-0.125775,0.166642,-0.085604,0.000379,0.043640
T_Z1_after,-0.420609,-0.304726,0.189162,-0.420609,-0.304726,0.189162,-0.420609,-0.304726,0.189162,0.246160,...,-0.041572,-0.089719,-0.009297,0.000312,-0.056038,0.026202,-0.112712,-0.033365,0.066204,0.077124
T_Z1_before,-0.260545,-0.418296,-0.250449,-0.260545,-0.418296,-0.250449,-0.260545,-0.418296,-0.250449,-0.010505,...,-0.099064,-0.094113,-0.008737,-0.057632,-0.051517,0.028541,0.050089,-0.104808,0.032642,0.080588
T_Z1_delta,0.191582,-0.112792,-0.489110,0.191582,-0.112792,-0.489110,0.191582,-0.112792,-0.489110,-0.297882,...,-0.061756,-0.000922,-0.009641,-0.063815,-0.007551,0.001411,0.185191,-0.077406,-0.040423,0.000445
action_result,0.207434,0.265633,0.091453,0.207434,0.265633,0.091453,0.207434,0.265633,0.091453,0.331242,...,1.000000,0.650060,-0.079706,0.484095,-0.057714,-0.281281,-0.456616,0.800856,-0.265998,-0.509104
bottom_icv_status_after,0.444092,0.440419,-0.009644,0.444092,0.440419,-0.009644,0.444092,0.440419,-0.009644,0.354550,...,0.650060,1.000000,-0.065408,0.609063,-0.047361,-0.158862,0.053939,0.657198,-0.260011,-0.781480
bottom_icv_status_before,0.350237,0.266300,-0.137401,0.350237,0.266300,-0.137401,0.350237,0.266300,-0.137401,0.219843,...,-0.079706,-0.065408,1.000000,0.369547,0.724080,0.022420,0.048291,-0.099526,0.053625,0.056135
command_type_0,0.460650,0.546888,0.134217,0.460650,0.546888,0.134217,0.460650,0.546888,0.134217,0.367365,...,0.484095,0.609063,0.369547,1.000000,0.029619,-0.129253,-0.164222,0.490724,-0.136257,-0.456349
command_type_1,0.244639,0.182636,-0.101376,0.244639,0.182636,-0.101376,0.244639,0.182636,-0.101376,0.167221,...,-0.057714,-0.047361,0.724080,0.029619,1.000000,0.016234,0.034966,-0.072065,0.038829,0.040646
command_type_2,-0.134403,-0.020221,0.184013,-0.134403,-0.020221,0.184013,-0.134403,-0.020221,0.184013,-0.116263,...,-0.281281,-0.158862,0.022420,-0.129253,0.016234,1.000000,-0.018489,-0.225266,-0.020531,-0.021492
command_type_3,0.104095,-0.042054,-0.234956,0.104095,-0.042054,-0.234956,0.104095,-0.042054,-0.234956,-0.141119,...,-0.456616,0.053939,0.048291,-0.164222,0.034966,-0.018489,1.000000,-0.485205,-0.044222,-0.046292
command_type_4,0.229944,0.294182,0.100936,0.229944,0.294182,0.100936,0.229944,0.294182,0.100936,0.336842,...,0.800856,0.657198,-0.099526,0.490724,-0.072065,-0.225266,-0.485205,1.000000,-0.538804,-0.564023
top_icv_status_after,-0.126731,-0.096359,0.049717,-0.126731,-0.096359,0.049717,-0.126731,-0.096359,0.049717,-0.074165,...,-0.265998,-0.260011,0.053625,-0.136257,0.038829,-0.020531,-0.044222,-0.538804,1.000000,-0.051406
top_icv_status_before,-0.280525,-0.332556,-0.080956,-0.280525,-0.332556,-0.080956,-0.280525,-0.332556,-0.080956,-0.295581,...,-0.509104,-0.781480,0.056135,-0.456349,0.040646,-0.021492,-0.046292,-0.564023,-0.051406,1.000000

In [6]:
synth_data.corr()

,P_WH_after,P_WH_before,P_WH_delta,P_Z0_after,P_Z0_before,P_Z0_delta,P_Z1_after,P_Z1_before,P_Z1_delta,P_bottom_after,...,action_result,bottom_icv_status_after,bottom_icv_status_before,command_type_0,command_type_1,command_type_2,command_type_3,command_type_4,top_icv_status_after,top_icv_status_before
P_WH_after,1.000000,0.988574,0.988788,0.988312,-0.021970,-0.022057,0.057880,0.057037,-0.062609,-0.055758,...,-0.001456,-0.071672,-0.001117,-0.012601,0.004094,-0.002951,0.002412,0.025769,-0.016985,-0.011066
P_WH_before,0.988574,1.000000,0.988731,0.988329,-0.022510,-0.022625,0.056885,0.057682,-0.062607,-0.055517,...,-0.000973,0.079498,-0.001459,0.006645,0.018000,-0.004937,0.001129,0.025204,-0.016084,-0.008060
P_WH_delta,0.988788,0.988731,1.000000,0.988423,-0.022447,-0.022607,0.057639,0.055584,-0.063156,-0.055608,...,-0.074401,0.003517,-0.001981,-0.007629,0.005161,-0.003650,-0.000716,0.028028,-0.016818,-0.009925
P_Z0_after,0.988312,0.988329,0.988423,1.000000,-0.023242,-0.023324,0.055597,0.055408,-0.062435,-0.056872,...,0.077763,0.004002,-0.001060,-0.000431,0.017965,-0.003989,0.000976,0.028355,-0.019115,-0.009321
P_Z0_before,-0.021970,-0.022510,-0.022447,-0.023242,1.000000,0.996413,0.092735,0.096358,0.084109,0.092687,...,-0.005265,-0.003657,-0.038034,0.002795,0.013609,-0.002563,0.000492,-0.010247,0.012463,0.000943
P_Z0_delta,-0.022057,-0.022625,-0.022607,-0.023324,0.996413,1.000000,0.093518,0.097531,0.085060,0.094257,...,-0.004751,-0.003848,0.046660,0.001962,0.005318,-0.001807,0.001161,-0.010476,0.010902,0.001345
P_Z1_after,0.057880,0.056885,0.057639,0.055597,0.092735,0.093518,1.000000,0.640352,0.517402,0.517677,...,-0.013323,-0.006358,0.009650,0.001652,-0.110415,0.005857,0.004047,-0.010307,-0.000968,0.002547
P_Z1_before,0.057037,0.057682,0.055584,0.055408,0.096358,0.097531,0.640352,1.000000,0.518318,0.528321,...,-0.001064,0.004489,0.014273,-0.003663,0.130662,0.007445,0.006431,-0.004833,-0.009474,0.001043
P_Z1_delta,-0.062609,-0.062607,-0.063156,-0.062435,0.084109,0.085060,0.517402,0.518318,1.000000,0.599081,...,0.004628,-0.000236,0.011595,0.009131,-0.098439,0.001599,-0.005104,-0.018574,0.002047,0.022183
P_bottom_after,-0.055758,-0.055517,-0.055608,-0.056872,0.092687,0.094257,0.517677,0.528321,0.599081,1.000000,...,-0.008402,0.001376,0.018947,0.009064,0.131412,-0.005282,0.011617,-0.018472,-0.003497,0.017886
P_bottom_before,0.005106,0.003076,0.003899,0.003599,0.005825,0.005315,0.000983,-0.001657,-0.017120,-0.012869,...,-0.001962,-0.013412,-0.006005,-0.284073,-0.403411,0.275917,0.272488,0.001044,0.277268,-0.832214
P_bottom_delta,-0.006155,-0.004430,-0.003569,-0.005303,0.007034,0.005994,0.000539,-0.006106,0.007598,-0.005206,...,-0.011400,0.011392,-0.012248,0.283639,0.395327,0.275917,-0.813965,0.001044,0.277268,0.254465
T_WH_after,0.006514,0.005249,0.005693,0.007073,-0.013227,-0.011784,-0.001029,0.003909,0.000772,0.003060,...,0.009079,-0.008349,0.016986,-0.481423,-0.195235,0.282377,0.278867,-0.004851,-0.827717,0.278775
T_WH_before,0.001983,0.002901,0.002101,0.001751,-0.004338,-0.003907,-0.000351,-0.010807,0.001442,0.010764,...,-0.002294,0.006081,0.005071,0.336673,0.140892,-0.465963,0.278941,-0.004717,-0.081936,0.278848
T_WH_delta,0.846306,0.838856,0.843015,0.840407,0.063814,0.064022,0.057384,0.057071,-0.048042,-0.042143,...,-0.015716,-0.045969,0.002723,-0.389481,-0.235532,0.170070,0.172136,0.012879,-0.268228,-0.086796
T_Z0_after,0.837574,0.845063,0.838140,0.841120,0.066065,0.065625,0.058739,0.054297,-0.041010,-0.035155,...,0.021003,0.052851,-0.004903,0.386755,0.255446,-0.249392,-0.069879,0.013737,0.146270,0.158048
T_Z0_before,0.823451,0.821008,0.823045,0.820889,-0.381710,-0.380151,0.228026,0.188215,0.113333,0.078532,...,-0.012777,-0.012921,0.016765,-0.107768,-0.155503,0.057451,0.057375,0.017113,-0.033046,-0.101015
T_Z0_delta,0.821921,0.824091,0.821870,0.823961,-0.375868,-0.377059,0.190674,0.230811,0.080348,0.121759,...,0.015130,0.017591,-0.015686,0.101993,0.176086,-0.017761,-0.087975,0.018486,0.038500,0.046308
T_Z1_after,0.017172,0.016733,0.016765,0.019311,0.000663,-0.000304,-0.001571,-0.000190,-0.012393,-0.018866,...,0.016763,-0.002835,-0.011412,-0.096239,-0.075726,-0.163862,-0.155269,0.573969,-0.162638,-0.156587
T_Z1_before,0.007682,0.007950,0.008461,0.006245,0.009531,0.010222,0.000025,0.010886,-0.448162,0.447291,...,-0.014551,0.001800,0.008202,-0.000079,0.256677,-0.007683,0.018671,0.000124,-0.006191,-0.004809
T_Z1_delta,-0.000439,0.001493,-0.001876,0.000313,0.005185,0.005655,-0.416116,0.431965,0.006083,0.017603,...,0.014384,0.012780,0.005566,-0.006276,0.284338,0.001937,0.002861,0.006382,-0.010079,-0.001756
action_result,-0.001456,-0.000973,-0.074401,0.077763,-0.005265,-0.004751,-0.013323,-0.001064,0.004628,-0.008402,...,1.000000,0.003192,0.006047,0.047300,0.084165,-0.002231,0.011121,0.002203,-0.015126,0.003957
bottom_icv_status_after,-0.071672,0.079498,0.003517,0.004002,-0.003657,-0.003848,-0.006358,0.004489,-0.000236,0.001376,...,0.003192,1.000000,-0.002264,0.127301,0.092033,-0.013150,-0.008483,-0.003636,0.005894,0.019845
bottom_icv_status_before,-0.001117,-0.001459,-0.001981,-0.001060,-0.038034,0.046660,0.009650,0.014273,0.011595,0.018947,...,0.006047,-0.002264,1.000000,-0.009822,-0.097847,0.008918,0.007907,-0.002747,-0.018378,0.004754
command_type_0,-0.012601,0.006645,-0.007629,-0.000431,0.002795,0.001962,0.001652,-0.003663,0.009131,0.009064,...,0.047300,0.127301,-0.009822,1.000000,0.632494,-0.540315,-0.311862,0.001084,0.534080,0.315366
command_type_1,0.004094,0.018000,0.005161,0.017965,0.013609,0.005318,-0.110415,0.130662,-0.098439,0.131412,...,0.084165,0.092033,-0.097847,0.632494,1.000000,-0.226588,-0.438460,0.004329,0.215770,0.443957
command_type_2,-0.002951,-0.004937,-0.003650,-0.003989,-0.002563,-0.001807,0.005857,0.007445,0.001599,-0.005282,...,-0.002231,-0.013150,0.008918,-0.540315,-0.226588,1.000000,-0.229699,-0.279481,-0.233728,-0.229622
command_type_3,0.002412,0.001129,-0.000716,0.000976,0.000492,0.001161,0.004047,0.006431,-0.005104,0.011617,...,0.011121,-0.008483,0.007907,-0.311862,-0.438460,-0.229699,1.000000,-0.276007,-0.230823,-0.226768
command_type_4,0.025769,0.025204,0.028028,0.028355,-0.010247,-0.010476,-0.010307,-0.004833,-0.018574,-0.018472,...,0.002203,-0.003636,-0.002747,0.001084,0.004329,-0.279481,-0.276007,1.000000,-0.280850,-0.275916
top_icv_status_after,-0.016985,-0.016084,-0.016818,-0.019115,0.012463,0.010902,-0.000968,-0.009474,0.002047,-0.003497,...,-0.015126,0.005894,-0.018378,0.534080,0.215770,-0.233728,-0.230823,-0.280850,1.000000,-0.230747
top_icv_status_before,-0.011066,-0.008060,-0.009925,-0.009321,0.000943,0.001345,0.002547,0.001043,0.022183,0.017886,...,0.003957,0.019845,0.004754,0.315366,0.443957,-0.229622,-0.226768,-0.275916,-0.230747,1.000000

In [7]:
pcd = abs(real_data.corr() - synth_data.corr())

In [8]:
pcd

,P_WH_after,P_WH_before,P_WH_delta,P_Z0_after,P_Z0_before,P_Z0_delta,P_Z1_after,P_Z1_before,P_Z1_delta,P_bottom_after,...,action_result,bottom_icv_status_after,bottom_icv_status_before,command_type_0,command_type_1,command_type_2,command_type_3,command_type_4,top_icv_status_after,top_icv_status_before
P_WH_after,0.000000,0.182455,1.307780,0.011688,0.828089,0.296935,0.942120,0.749081,0.256383,0.260290,...,0.208890,0.515764,0.351354,0.473251,0.240545,0.131452,0.101683,0.204175,0.109746,0.269460
P_WH_before,0.182455,0.000000,0.685037,0.182211,1.022510,0.326320,0.749233,0.942318,0.366302,0.343638,...,0.266605,0.360920,0.267759,0.540243,0.164636,0.015284,0.043183,0.268978,0.080275,0.324496
P_WH_delta,1.307780,0.685037,0.000000,1.307415,0.326141,1.022607,0.376631,0.248110,1.063156,0.187751,...,0.165855,0.013161,0.135420,0.141846,0.106537,0.187663,0.234240,0.072909,0.066535,0.071031
P_Z0_after,0.011688,0.182211,1.307415,0.000000,0.829361,0.295669,0.944403,0.750710,0.256557,0.261404,...,0.129672,0.440090,0.351297,0.461081,0.226674,0.130414,0.103119,0.201589,0.107616,0.271205
P_Z0_before,0.828089,1.022510,0.326141,0.829361,0.000000,0.692719,0.713384,0.903642,0.219585,0.195434,...,0.270897,0.444076,0.304334,0.544093,0.169028,0.017658,0.042546,0.304429,0.108822,0.333499
P_Z0_delta,0.296935,0.326320,1.022607,0.295669,0.692719,0.000000,0.412510,0.206163,0.914940,0.037886,...,0.096204,0.005796,0.184061,0.132255,0.106694,0.185820,0.236118,0.111412,0.038815,0.082302
P_Z1_after,0.942120,0.749233,0.376631,0.944403,0.713384,0.412510,0.000000,0.165766,0.836395,0.313145,...,0.220757,0.450450,0.340587,0.458998,0.355054,0.140260,0.100048,0.240251,0.125763,0.283073
P_Z1_before,0.749081,0.942318,0.248110,0.750710,0.903642,0.206163,0.165766,0.000000,0.214623,0.240201,...,0.266696,0.435930,0.252027,0.550550,0.051974,0.027667,0.048485,0.299015,0.086885,0.333599
P_Z1_delta,0.256383,0.366302,1.063156,0.256557,0.219585,0.914940,0.836395,0.214623,0.000000,0.466938,...,0.086825,0.009408,0.148996,0.125086,0.002937,0.182413,0.229852,0.119510,0.047670,0.103139
P_bottom_after,0.260290,0.343638,0.187751,0.261404,0.195434,0.037886,0.313145,0.240201,0.466938,0.000000,...,0.339644,0.353174,0.200896,0.358301,0.035809,0.110981,0.152736,0.355314,0.070668,0.313467
P_bottom_before,0.317012,0.205685,0.188180,0.318518,0.202935,0.189596,0.321134,0.210418,0.167161,0.789804,...,0.293629,0.336701,0.253298,0.611813,0.620980,0.393956,0.336315,0.300326,0.403536,0.576672
P_bottom_delta,0.123729,0.063928,0.295216,0.122877,0.075392,0.304780,0.117035,0.062251,0.306384,0.371843,...,0.043826,0.056379,0.118477,0.394568,0.459659,0.279160,0.925614,0.047911,0.359784,0.196376
T_WH_after,0.826716,0.642233,0.294696,0.827275,0.623757,0.312172,0.819173,0.640894,0.299617,0.228020,...,0.130271,0.412824,0.354539,0.049777,0.044870,0.126142,0.514930,0.150456,0.960176,0.017079
T_WH_before,0.562828,0.616549,0.081920,0.562597,0.609311,0.075912,0.560495,0.602841,0.081260,0.270421,...,0.166896,0.319868,0.226989,0.718578,0.296969,0.495462,0.307304,0.187518,0.178782,0.052156
T_WH_delta,0.694970,0.902213,1.188152,0.689071,0.127172,0.409159,0.093953,0.120428,0.297095,0.038038,...,0.043118,0.103221,0.148120,0.449965,0.282587,0.278510,0.028288,0.081236,0.294608,0.041237
T_Z0_after,1.765192,1.608985,0.568107,1.768739,0.829987,0.204409,0.986357,0.818219,0.311044,0.231639,...,0.162846,0.464193,0.320003,0.821331,0.483580,0.397313,0.099573,0.188059,0.038318,0.102950
T_Z0_before,1.449531,1.494578,0.893802,1.446969,0.291859,0.309394,0.854105,0.861785,0.184089,0.357321,...,0.156787,0.287051,0.224046,0.255244,0.010869,0.041489,0.054685,0.210472,0.114019,0.323309
T_Z0_delta,0.788607,0.975043,1.117276,0.790646,0.224915,0.081653,0.157360,0.381764,0.375753,0.265731,...,0.101716,0.019058,0.038656,0.166199,0.273640,0.108014,0.254617,0.104090,0.038121,0.002667
T_Z1_after,0.437780,0.321459,0.172397,0.439920,0.305388,0.189465,0.419038,0.304536,0.201555,0.265026,...,0.058335,0.086884,0.002115,0.096551,0.019687,0.190064,0.042557,0.607334,0.228842,0.233711
T_Z1_before,0.268227,0.426246,0.258911,0.266790,0.427827,0.260671,0.260569,0.429183,0.197713,0.457796,...,0.084513,0.095913,0.016940,0.057553,0.308195,0.036224,0.031418,0.104932,0.038833,0.085397
T_Z1_delta,0.192021,0.114285,0.487234,0.191269,0.117977,0.494765,0.607698,0.544757,0.495192,0.315485,...,0.076140,0.013703,0.015208,0.057539,0.291889,0.000526,0.182330,0.083788,0.030344,0.002201
action_result,0.208890,0.266605,0.165855,0.129672,0.270897,0.096204,0.220757,0.266696,0.086825,0.339644,...,0.000000,0.646869,0.085753,0.436795,0.141879,0.279051,0.467737,0.798653,0.250872,0.513062
bottom_icv_status_after,0.515764,0.360920,0.013161,0.440090,0.444076,0.005796,0.450450,0.435930,0.009408,0.353174,...,0.646869,0.000000,0.063145,0.481762,0.139394,0.145712,0.062422,0.660834,0.265905,0.801325
bottom_icv_status_before,0.351354,0.267759,0.135420,0.351297,0.304334,0.184061,0.340587,0.252027,0.148996,0.200896,...,0.085753,0.063145,0.000000,0.379370,0.821927,0.013502,0.040383,0.096779,0.072003,0.051381
command_type_0,0.473251,0.540243,0.141846,0.461081,0.544093,0.132255,0.458998,0.550550,0.125086,0.358301,...,0.436795,0.481762,0.379370,0.000000,0.602875,0.411063,0.147640,0.489640,0.670338,0.771715
command_type_1,0.240545,0.164636,0.106537,0.226674,0.169028,0.106694,0.355054,0.051974,0.002937,0.035809,...,0.141879,0.139394,0.821927,0.602875,0.000000,0.242822,0.473426,0.076394,0.176942,0.403311
command_type_2,0.131452,0.015284,0.187663,0.130414,0.017658,0.185820,0.140260,0.027667,0.182413,0.110981,...,0.279051,0.145712,0.013502,0.411063,0.242822,0.000000,0.211210,0.054215,0.213197,0.208130
command_type_3,0.101683,0.043183,0.234240,0.103119,0.042546,0.236118,0.100048,0.048485,0.229852,0.152736,...,0.467737,0.062422,0.040383,0.147640,0.473426,0.211210,0.000000,0.209198,0.186601,0.180476
command_type_4,0.204175,0.268978,0.072909,0.201589,0.304429,0.111412,0.240251,0.299015,0.119510,0.355314,...,0.798653,0.660834,0.096779,0.489640,0.076394,0.054215,0.209198,0.000000,0.257954,0.288107
top_icv_status_after,0.109746,0.080275,0.066535,0.107616,0.108822,0.038815,0.125763,0.086885,0.047670,0.070668,...,0.250872,0.265905,0.072003,0.670338,0.176942,0.213197,0.186601,0.257954,0.000000,0.179341
top_icv_status_before,0.269460,0.324496,0.071031,0.271205,0.333499,0.082302,0.283073,0.333599,0.103139,0.313467,...,0.513062,0.801325,0.051381,0.771715,0.403311,0.208130,0.180476,0.288107,0.179341,0.000000

In [ ]:
plt.figure(figsize=(20, 10))
heatmap = sns.heatmap(pcd, vmin=0, vmax=1, annot=True, cmap='GnBu')
heatmap.set_title('Pairwise Correlation Difference Heatmap', fontdict={'fontsize':18}, pad=12);

In [ ]:
pcd.sum().sort_values(ascending=False)

'''
P_Z1                 5.746289
P_Z0                 5.229042
P_WH                 5.227871
action_result        5.008311
T_Z0                 4.977033
T_WH                 4.946675
T_Z1                 4.300884
bottom_icv_status    3.929534
top_icv_status       2.499192
P_bottom             2.363101
delta                2.207578
Type                 1.812296
dtype: float64
'''

## Sweetviz comparison

In [ ]:
real = real_data.astype('float64')
synth = synth_data.astype('float64')

In [ ]:
real

In [ ]:
synth

In [ ]:
real.columns

In [ ]:
feature_config = sv.FeatureConfig(force_num=['P_WH_after', 'P_WH_before', 'P_WH_delta', 'P_Z0_after', 'P_Z0_before',
       'P_Z0_delta', 'P_Z1_after', 'P_Z1_before', 'P_Z1_delta',
       'P_bottom_after', 'P_bottom_before', 'P_bottom_delta', 'T_WH_after',
       'T_WH_before', 'T_WH_delta', 'T_Z0_after', 'T_Z0_before', 'T_Z0_delta',
       'T_Z1_after', 'T_Z1_before', 'T_Z1_delta'], skip=['action_result',
       'bottom_icv_status_after', 'bottom_icv_status_before', 'command_type_0',
       'command_type_1', 'command_type_2', 'command_type_3', 'command_type_4',
       'top_icv_status_after', 'top_icv_status_before'])

In [ ]:
my_report = sv.compare([synth, "Synthetic Data"], [real, "Real Data"], feat_cfg=feature_config)

In [ ]:
my_report.show_html(filepath='Synth_vs_Real_REPORT.html')